FROM mcr.microsoft.com/devcontainers/javascript-node:0-18
RUN sudo apt update -y && sudo apt install -y libgtk2.0-0 libgtk-3-0 libgbm-dev libnotify-dev libgconf-2-4 libnss3 libxss1 libasound2 libxtst6 xauth xvfb
